# Generated by Django 5.0.1 on 2025-02-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_imageupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='enhanced_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
