# Generated by Django 5.1 on 2025-03-02 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='detected_images/', verbose_name='Uploaded Image')),
                ('image_url', models.URLField(max_length=255, verbose_name='Image URL')),
                ('questions_answers', models.JSONField(verbose_name='Question and Answers')),
                ('model_accuracy', models.FloatField(default=96, verbose_name='Model Accuracy')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user')),
            ],
        ),
    ]
