# Generated by Django 5.1 on 2024-09-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="bert_model",
            fields=[
                ("S_No", models.AutoField(primary_key=True, serialize=False)),
                ("model_accuracy", models.CharField(default="96.0", max_length=10)),
            ],
            options={
                "db_table": "bert_model",
            },
        ),
        migrations.CreateModel(
            name="cnn_model",
            fields=[
                ("S_No", models.AutoField(primary_key=True, serialize=False)),
                ("model_accuracy", models.CharField(default="98.4", max_length=10)),
            ],
            options={
                "db_table": "cnn_model",
            },
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="datasets/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "dataset_table",
            },
        ),
        migrations.CreateModel(
            name="Efficient_model",
            fields=[
                ("S_No", models.AutoField(primary_key=True, serialize=False)),
                ("model_accuracy", models.CharField(default="98.6", max_length=10)),
            ],
            options={
                "db_table": "Efficient_model",
            },
        ),
    ]
